### ISSUE TITLE
create-empty-blocks param does not appear to be under consensus.

### ISSUE THREAD

**Issue by erikdies** [vulcanize/cosmos-sdk#27]
## Summary of Bug

When creating a testnet, the `create-empty-blocks` param does not appear to be under consensus.  When one of the nodes proposes an empty block, regardless of the config on the other nodes, an empty block is produced.

### TODO
 - [ ] Check to see if the param does anything, i.e. if all nodes have `create-empty-blocks` set to false are empty blocks created

EDIT - apparently this is known, previous issues:
 - https://github.com/cosmos/cosmos-sdk/issues/1571
 - https://github.com/cosmos/cosmos-sdk/issues/10240
 - https://github.com/cosmos/cosmos-sdk/pull/4624
 
## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
